import { useParams, useNavigate } from 'react-router-dom';
import { useState } from 'react';

export default function ProjectMemo() {
    const { id } = useParams();
    const navigate = useNavigate();
    const [showEmailModal, setShowEmailModal] = useState(false);
    const [emailAddress, setEmailAddress] = useState('');
    const [emailMessage, setEmailMessage] = useState('');
    const [isSending, setIsSending] = useState(false);
    const [sendStatus, setSendStatus] = useState<'idle' | 'success' | 'error'>('idle');

    // Mock project data - in production, fetch from API
    const project = {
        id: id || '8492',
        name: 'West African Rail Expansion',
        status: 'Feasibility Phase',
        fundingAsk: '$450M',
        readinessScore: 85,
        pillar: 'Infrastructure',
        leadCountry: 'Nigeria',
        leadCompany: 'RailCo Ltd.'
    };

    const handleDownload = () => {
        // Implement PDF download logic
        console.log('Downloading memo as PDF...');
    };

    const handleEmail = () => {
        setShowEmailModal(true);
        setSendStatus('idle');
        setEmailAddress('');
        setEmailMessage('');
    };

    const handleSendEmail = async () => {
        if (!emailAddress || !emailAddress.includes('@')) {
            alert('Please enter a valid email address');
            return;
        }

        setIsSending(true);
        setSendStatus('idle');

        try {
            // Prepare the memo content
            const memoContent = `
INVESTMENT MEMORANDUM

Project: ${project.name}
Project ID: #${project.id}
Generated: ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}

EXECUTIVE SUMMARY
================
The ${project.name} represents a strategic infrastructure initiative aimed at enhancing regional connectivity and economic integration across the ECOWAS region. With a funding requirement of ${project.fundingAsk}, this project aligns with the broader Vision 2050 objectives of integrated infrastructure development.

The project has achieved a readiness score of ${project.readinessScore}/100, indicating strong preparedness for investment consideration. Key stakeholders including the African Development Bank have expressed preliminary support, and technical assessments confirm feasibility with manageable risk factors.

INVESTMENT HIGHLIGHTS
====================
• Economic Impact: Projected IRR of 14% over 25 years with significant job creation potential
• Regional Connectivity: Direct alignment with ECOWAS Vision 2050 Goal 3, reducing transit times by 40%
• Environmental Benefits: Reduction of 150k tons of carbon emissions annually
• Stakeholder Support: Preliminary backing from AfDB and strong member state commitment

RISK ASSESSMENT & MITIGATION
============================
Urban Displacement Risk (Medium): Potential displacement in Lagos suburbs requires comprehensive resettlement action plan with fair compensation mechanisms.

Environmental Compliance (Low): EIA requires updating - addendum in progress, expected completion within 30 days.

FINANCIAL OVERVIEW
==================
Total Investment Required: ${project.fundingAsk} USD
Projected IRR: 14%
Investment Period: 25 Years
Current Phase: ${project.status}

RECOMMENDATION
==============
PROCEED TO INVESTMENT COMMITTEE REVIEW

Based on comprehensive analysis, this project demonstrates strong alignment with ECOWAS strategic objectives, solid financial fundamentals, and manageable risk profile. The high readiness score of ${project.readinessScore}/100 indicates preparedness for advancement to the next stage.

Recommended Action: Advance to Investment Committee for formal approval pending completion of updated EIA documentation.

---
Generated by ECOWAS AI Agent System
            `.trim();

            // Call the supervisor agent to send email
            const response = await fetch('/api/v1/agents/supervisor/send-email', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${localStorage.getItem('token')}`
                },
                body: JSON.stringify({
                    to_email: emailAddress,
                    subject: `Investment Memo: ${project.name}`,
                    body: emailMessage || `Please find attached the investment memorandum for ${project.name}.`,
                    memo_content: memoContent,
                    project_id: project.id,
                    project_name: project.name
                })
            });

            if (!response.ok) {
                throw new Error('Failed to send email');
            }

            const data = await response.json();
            console.log('Email send response:', data);
            setSendStatus('success');

            // Close modal after 3 seconds to allow reading the message
            setTimeout(() => {
                setShowEmailModal(false);
                setEmailAddress('');
                setEmailMessage('');
            }, 3000);
        } catch (error) {
            console.error('Error sending email:', error);
            setSendStatus('error');
        } finally {
            setIsSending(false);
        }
    };

    return (
        <div style={{ padding: '32px 40px', background: 'var(--bg)', minHeight: '100vh', fontFamily: "'Geist', 'Inter', system-ui, sans-serif" }}>
            <div style={{ maxWidth: 900, margin: '0 auto' }}>
                {/* Breadcrumbs */}
                <div style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 12, color: 'var(--ink-500)', marginBottom: 24 }}>
                    <button onClick={() => navigate('/dashboard')} style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--ink-500)', fontSize: 12, fontFamily: "'Geist', 'Inter', system-ui, sans-serif" }}>Home</button>
                    <span style={{ color: 'var(--ink-300)' }}>›</span>
                    <button onClick={() => navigate('/deal-pipeline')} style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--ink-500)', fontSize: 12, fontFamily: "'Geist', 'Inter', system-ui, sans-serif" }}>Deal Pipeline</button>
                    <span style={{ color: 'var(--ink-300)' }}>›</span>
                    <button onClick={() => navigate(`/deal-pipeline/${id}`)} style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--ink-500)', fontSize: 12, fontFamily: "'Geist', 'Inter', system-ui, sans-serif" }}>{project.name}</button>
                    <span style={{ color: 'var(--ink-300)' }}>›</span>
                    <span style={{ color: 'var(--ink-900)', fontWeight: 500 }}>Investment Memo</span>
                </div>

                {/* Page Header */}
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 16, marginBottom: 32 }}>
                    <div>
                        <span style={{ fontSize: 10, color: 'var(--ink-500)', letterSpacing: '0.08em', textTransform: 'uppercase', display: 'block', marginBottom: 8, fontFamily: "'Geist Mono', monospace" }}>INVESTMENT MEMORANDUM</span>
                        <h1 style={{ fontFamily: "'Source Serif 4', Georgia, serif", fontSize: 36, fontWeight: 600, color: 'var(--ink-900)', margin: 0, lineHeight: 1.2 }}>
                            AI-Generated Investment Memo
                        </h1>
                        <p style={{ fontSize: 13, color: 'var(--ink-500)', marginTop: 6 }}>Generated for: {project.name}</p>
                    </div>
                    <div style={{ display: 'flex', gap: 8 }}>
                        <button onClick={handleEmail} style={{ padding: '8px 16px', fontSize: 13, fontWeight: 500, border: '1px solid var(--border)', background: 'var(--surface)', color: 'var(--ink-600)', cursor: 'pointer', fontFamily: "'Geist', 'Inter', system-ui, sans-serif", display: 'flex', alignItems: 'center', gap: 6 }}>
                            <span className="material-symbols-outlined" style={{ fontSize: 16 }}>email</span>
                            Email
                        </button>
                        <button onClick={handleDownload} style={{ padding: '8px 16px', fontSize: 13, fontWeight: 500, border: 'none', background: 'var(--accent)', color: 'var(--accent-ink)', cursor: 'pointer', fontFamily: "'Geist', 'Inter', system-ui, sans-serif", display: 'flex', alignItems: 'center', gap: 6 }}>
                            <span className="material-symbols-outlined" style={{ fontSize: 16 }}>download</span>
                            Download PDF
                        </button>
                    </div>
                </div>

                {/* AI Notice Banner — Martin notes strip */}
                <div style={{ borderLeft: '2px solid var(--accent)', background: 'var(--accent-soft)', padding: '16px 20px', marginBottom: 32 }}>
                    <p style={{ fontSize: 13, color: 'var(--ink-700)', margin: 0, fontFamily: "'Source Serif 4', Georgia, serif" }}>
                        <em style={{ fontStyle: 'italic', fontWeight: 600 }}>Martin notes</em> — This memo was automatically generated. Please review before sharing.
                    </p>
                </div>

                {/* Memo Document */}
                <div style={{ background: 'var(--surface)', border: '1px solid var(--border)', padding: '48px 56px', marginBottom: 32 }}>
                    {/* Memo Header */}
                    <div style={{ borderBottom: '1px solid var(--border)', paddingBottom: 24, marginBottom: 32 }}>
                        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 16 }}>
                            <div>
                                <h2 style={{ fontFamily: "'Source Serif 4', Georgia, serif", fontSize: 20, fontWeight: 600, color: 'var(--ink-900)', margin: '0 0 4px' }}>INVESTMENT MEMORANDUM</h2>
                                <p style={{ fontSize: 12, color: 'var(--ink-400)', margin: 0, fontFamily: "'Geist Mono', monospace" }}>Project ID: #{project.id}</p>
                            </div>
                            <div style={{ textAlign: 'right' }}>
                                <p style={{ fontSize: 12, color: 'var(--ink-400)', margin: '0 0 4px', fontFamily: "'Geist Mono', monospace" }}>Generated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>
                                <p style={{ fontSize: 11, color: 'var(--ink-400)', margin: 0, fontFamily: "'Geist', 'Inter', system-ui, sans-serif" }}>AI Generated</p>
                            </div>
                        </div>
                        <h3 style={{ fontFamily: "'Source Serif 4', Georgia, serif", fontSize: 18, fontWeight: 600, color: 'var(--ink-900)', margin: '0 0 4px' }}>{project.name}</h3>
                        <p style={{ fontSize: 12, color: 'var(--ink-400)', margin: 0, fontFamily: "'Geist', 'Inter', system-ui, sans-serif" }}>{project.pillar} · {project.leadCountry}</p>
                    </div>

                    {/* Executive Summary */}
                    <section style={{ marginBottom: 32 }}>
                        <p style={{ fontSize: 16, fontWeight: 500, color: 'var(--ink-900)', margin: '0 0 12px', fontFamily: "'Geist', 'Inter', system-ui, sans-serif" }}>Executive Summary</p>
                        <div style={{ color: 'var(--ink-700)', fontSize: 15, lineHeight: 1.8, fontFamily: "'Source Serif 4', Georgia, serif" }}>
                            <p style={{ margin: '0 0 12px' }}>
                                The {project.name} represents a strategic infrastructure initiative aimed at enhancing regional connectivity and economic integration across the ECOWAS region. With a funding requirement of {project.fundingAsk}, this project aligns with the broader Vision 2050 objectives of integrated infrastructure development.
                            </p>
                            <p style={{ margin: 0 }}>
                                The project has achieved a readiness score of {project.readinessScore}/100, indicating strong preparedness for investment consideration. Key stakeholders including the African Development Bank have expressed preliminary support, and technical assessments confirm feasibility with manageable risk factors.
                            </p>
                        </div>
                    </section>

                    {/* Investment Highlights */}
                    <section style={{ marginBottom: 32 }}>
                        <p style={{ fontSize: 16, fontWeight: 500, color: 'var(--ink-900)', margin: '0 0 16px', fontFamily: "'Geist', 'Inter', system-ui, sans-serif" }}>Investment Highlights</p>
                        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
                            {[
                                { icon: 'trending_up', title: 'Economic Impact', body: 'Projected IRR of 14% over 25 years with significant job creation potential across the region.' },
                                { icon: 'hub', title: 'Regional Connectivity', body: 'Direct alignment with ECOWAS Vision 2050 Goal 3, reducing transit times by 40%.' },
                                { icon: 'eco', title: 'Environmental Benefits', body: 'Reduction of 150k tons of carbon emissions annually through modal shift from road to rail.' },
                                { icon: 'verified', title: 'Stakeholder Support', body: 'Preliminary backing from AfDB and strong commitment from member states.' },
                            ].map(item => (
                                <div key={item.title} style={{ border: '1px solid var(--border)', padding: 16 }}>
                                    <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8 }}>
                                        <span className="material-symbols-outlined" style={{ fontSize: 18, color: 'var(--ink-500)' }}>{item.icon}</span>
                                        <p style={{ fontSize: 13, fontWeight: 600, color: 'var(--ink-900)', margin: 0, fontFamily: "'Geist', 'Inter', system-ui, sans-serif" }}>{item.title}</p>
                                    </div>
                                    <p style={{ fontSize: 13, color: 'var(--ink-600)', margin: 0, lineHeight: 1.6, fontFamily: "'Geist', 'Inter', system-ui, sans-serif" }}>{item.body}</p>
                                </div>
                            ))}
                        </div>
                    </section>

                    {/* Risk Assessment */}
                    <section style={{ marginBottom: 32 }}>
                        <p style={{ fontSize: 16, fontWeight: 500, color: 'var(--ink-900)', margin: '0 0 16px', fontFamily: "'Geist', 'Inter', system-ui, sans-serif" }}>Risk Assessment & Mitigation</p>
                        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
                            {[
                                {
                                    dotColor: 'var(--amber)',
                                    title: 'Urban Displacement Risk — Medium',
                                    desc: 'Potential displacement of communities in Lagos suburban areas requires careful management.',
                                    mitigation: 'Comprehensive resettlement action plan with fair compensation mechanisms and community engagement programs.'
                                },
                                {
                                    dotColor: 'var(--amber)',
                                    title: 'Environmental Compliance — Low',
                                    desc: 'Environmental Impact Assessment requires updating as current version is over 6 months old.',
                                    mitigation: 'Updated EIA addendum currently in progress with TWG lead, expected completion within 30 days.'
                                },
                            ].map(item => (
                                <div key={item.title} style={{ display: 'flex', gap: 16, alignItems: 'flex-start', padding: '12px 0', borderBottom: '1px solid var(--border)' }}>
                                    <div style={{ width: 6, height: 6, borderRadius: 6, background: item.dotColor, flexShrink: 0, marginTop: 6 }} />
                                    <div style={{ flex: 1 }}>
                                        <p style={{ fontSize: 13, fontWeight: 600, color: 'var(--ink-900)', margin: '0 0 4px', fontFamily: "'Geist', 'Inter', system-ui, sans-serif" }}>{item.title}</p>
                                        <p style={{ fontSize: 13, color: 'var(--ink-600)', margin: '0 0 8px', lineHeight: 1.6, fontFamily: "'Source Serif 4', Georgia, serif" }}>{item.desc}</p>
                                        <p style={{ fontSize: 13, color: 'var(--ink-800)', margin: 0, lineHeight: 1.6, fontFamily: "'Geist', 'Inter', system-ui, sans-serif" }}>
                                            <strong>Mitigation:</strong> {item.mitigation}
                                        </p>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </section>

                    {/* Financial Overview */}
                    <section style={{ marginBottom: 32 }}>
                        <p style={{ fontSize: 16, fontWeight: 500, color: 'var(--ink-900)', margin: '0 0 16px', fontFamily: "'Geist', 'Inter', system-ui, sans-serif" }}>Financial Overview</p>
                        <div>
                            {[
                                { label: 'Total Investment Required', value: `${project.fundingAsk} USD`, large: true },
                                { label: 'Projected IRR', value: '14%', green: true },
                                { label: 'Investment Period', value: '25 Years' },
                                { label: 'Current Phase', value: project.status },
                            ].map((row, i) => (
                                <div key={row.label} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '14px 0', borderBottom: i < 3 ? '1px solid var(--border)' : 'none' }}>
                                    <span style={{ fontSize: 13, color: 'var(--ink-600)', fontFamily: "'Geist', 'Inter', system-ui, sans-serif" }}>{row.label}</span>
                                    <span style={{
                                        fontFamily: row.large ? "'Source Serif 4', Georgia, serif" : "'Geist', 'Inter', system-ui, sans-serif",
                                        fontSize: row.large ? 20 : 14,
                                        fontWeight: 600,
                                        color: row.green ? 'var(--sage)' : 'var(--ink-900)'
                                    }}>{row.value}</span>
                                </div>
                            ))}
                        </div>
                    </section>

                    {/* Recommendation */}
                    <section style={{ marginBottom: 32 }}>
                        <p style={{ fontSize: 16, fontWeight: 500, color: 'var(--ink-900)', margin: '0 0 16px', fontFamily: "'Geist', 'Inter', system-ui, sans-serif" }}>Recommendation</p>
                        <div style={{ borderLeft: '2px solid var(--sage)', background: 'var(--surface)', padding: 24, border: '1px solid var(--border)', borderLeftWidth: 2, borderLeftColor: 'var(--sage)' }}>
                            <h5 style={{ fontFamily: "'Source Serif 4', Georgia, serif", fontSize: 18, color: 'var(--sage)', margin: '0 0 12px', fontWeight: 600 }}>PROCEED TO INVESTMENT COMMITTEE REVIEW</h5>
                            <p style={{ fontSize: 14, color: 'var(--ink-600)', margin: '0 0 12px', lineHeight: 1.7, fontFamily: "'Source Serif 4', Georgia, serif" }}>
                                Based on the comprehensive analysis, this project demonstrates strong alignment with ECOWAS strategic objectives, solid financial fundamentals, and manageable risk profile. The high readiness score of {project.readinessScore}/100 indicates preparedness for advancement to the next stage.
                            </p>
                            <p style={{ fontSize: 13, fontWeight: 600, color: 'var(--ink-900)', margin: 0, fontFamily: "'Geist', 'Inter', system-ui, sans-serif" }}>
                                Recommended Action: Advance to Investment Committee for formal approval pending completion of updated EIA documentation.
                            </p>
                        </div>
                    </section>

                    {/* Memo Footer */}
                    <div style={{ borderTop: '1px solid var(--border)', paddingTop: 20, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                        <span style={{ fontSize: 11, color: 'var(--ink-400)', fontFamily: "'Geist', 'Inter', system-ui, sans-serif" }}>Generated by ECOWAS AI Agent System</span>
                        <span style={{ fontSize: 11, color: 'var(--ink-400)', fontFamily: "'Geist Mono', monospace" }}>Page 1 of 1</span>
                    </div>
                </div>

                {/* Bottom Actions */}
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <button onClick={() => navigate(`/deal-pipeline/${id}`)} style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 13, color: 'var(--ink-500)', background: 'none', border: 'none', cursor: 'pointer', fontFamily: "'Geist', 'Inter', system-ui, sans-serif" }}>
                        <span className="material-symbols-outlined" style={{ fontSize: 18 }}>arrow_back</span>
                        Back to Project Details
                    </button>
                    <button style={{ padding: '8px 20px', fontSize: 13, fontWeight: 500, background: 'var(--accent)', color: 'var(--accent-ink)', border: 'none', cursor: 'pointer', fontFamily: "'Geist', 'Inter', system-ui, sans-serif", display: 'flex', alignItems: 'center', gap: 6 }}>
                        <span className="material-symbols-outlined" style={{ fontSize: 16 }}>edit</span>
                        Edit Memo
                    </button>
                </div>
            </div>

            {/* Email Modal */}
            {showEmailModal && (
                <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.5)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 50, padding: 16 }}>
                    <div style={{ background: 'var(--surface)', border: '1px solid var(--border)', maxWidth: 440, width: '100%' }}>
                        {/* Modal Header */}
                        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '20px 24px', borderBottom: '1px solid var(--border)' }}>
                            <h3 style={{ fontSize: 16, fontWeight: 600, color: 'var(--ink-900)', margin: 0, fontFamily: "'Geist', 'Inter', system-ui, sans-serif" }}>Email Investment Memo</h3>
                            <button onClick={() => setShowEmailModal(false)} style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--ink-400)', fontSize: 20, lineHeight: 1 }}>×</button>
                        </div>

                        {/* Modal Body */}
                        <div style={{ padding: '20px 24px' }}>
                            {sendStatus === 'idle' && (
                                <>
                                    <div style={{ marginBottom: 16 }}>
                                        <label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: 'var(--ink-900)', marginBottom: 6, fontFamily: "'Geist', 'Inter', system-ui, sans-serif" }}>
                                            Recipient Email Address *
                                        </label>
                                        <input
                                            type="email"
                                            value={emailAddress}
                                            onChange={(e) => setEmailAddress(e.target.value)}
                                            placeholder="stakeholder@example.com"
                                            style={{ width: '100%', padding: '8px 12px', border: '1px solid var(--border)', background: 'var(--surface)', fontSize: 13, color: 'var(--ink-900)', outline: 'none', fontFamily: "'Geist', 'Inter', system-ui, sans-serif", boxSizing: 'border-box' }}
                                            disabled={isSending}
                                        />
                                    </div>

                                    <div style={{ marginBottom: 16 }}>
                                        <label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: 'var(--ink-900)', marginBottom: 6, fontFamily: "'Geist', 'Inter', system-ui, sans-serif" }}>
                                            Custom Message (Optional)
                                        </label>
                                        <textarea
                                            value={emailMessage}
                                            onChange={(e) => setEmailMessage(e.target.value)}
                                            placeholder="Add a personal message to accompany the memo..."
                                            rows={4}
                                            style={{ width: '100%', padding: '8px 12px', border: '1px solid var(--border)', background: 'var(--surface)', fontSize: 13, color: 'var(--ink-900)', outline: 'none', resize: 'none', fontFamily: "'Geist', 'Inter', system-ui, sans-serif", boxSizing: 'border-box' }}
                                            disabled={isSending}
                                        />
                                    </div>

                                    <div style={{ borderLeft: '2px solid var(--accent)', paddingLeft: 12, background: 'var(--accent-soft)', padding: '10px 12px' }}>
                                        <p style={{ fontSize: 11, color: 'var(--ink-600)', margin: 0, fontFamily: "'Geist', 'Inter', system-ui, sans-serif" }}>
                                            The AI-generated memo will be sent via the ECOWAS AI Agent system using Gmail integration.
                                        </p>
                                    </div>
                                </>
                            )}

                            {sendStatus === 'success' && (
                                <div style={{ padding: '32px 0', textAlign: 'center' }}>
                                    <div style={{ width: 48, height: 48, borderRadius: 48, background: 'var(--accent-soft)', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 16px' }}>
                                        <span className="material-symbols-outlined" style={{ color: 'var(--sage)', fontSize: 28 }}>check_circle</span>
                                    </div>
                                    <p style={{ fontSize: 15, fontWeight: 600, color: 'var(--ink-900)', margin: '0 0 6px', fontFamily: "'Source Serif 4', Georgia, serif" }}>Email Sent Successfully!</p>
                                    <p style={{ fontSize: 13, color: 'var(--ink-500)', margin: 0, fontFamily: "'Geist', 'Inter', system-ui, sans-serif" }}>
                                        The investment memo has been sent to {emailAddress}
                                    </p>
                                </div>
                            )}

                            {sendStatus === 'error' && (
                                <div style={{ padding: '32px 0', textAlign: 'center' }}>
                                    <div style={{ width: 48, height: 48, borderRadius: 48, background: 'var(--accent-soft)', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 16px' }}>
                                        <span className="material-symbols-outlined" style={{ color: 'var(--terra)', fontSize: 28 }}>error</span>
                                    </div>
                                    <p style={{ fontSize: 15, fontWeight: 600, color: 'var(--ink-900)', margin: '0 0 6px', fontFamily: "'Source Serif 4', Georgia, serif" }}>Failed to Send Email</p>
                                    <p style={{ fontSize: 13, color: 'var(--ink-500)', margin: '0 0 16px', fontFamily: "'Geist', 'Inter', system-ui, sans-serif" }}>
                                        There was an error sending the email. Please try again.
                                    </p>
                                    <button
                                        onClick={() => setSendStatus('idle')}
                                        style={{ fontSize: 13, color: 'var(--accent)', background: 'none', border: 'none', cursor: 'pointer', fontFamily: "'Geist', 'Inter', system-ui, sans-serif' " }}
                                    >
                                        Try Again
                                    </button>
                                </div>
                            )}
                        </div>

                        {/* Modal Footer */}
                        {sendStatus === 'idle' && (
                            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'flex-end', gap: 8, padding: '16px 24px', borderTop: '1px solid var(--border)' }}>
                                <button
                                    onClick={() => setShowEmailModal(false)}
                                    style={{ padding: '7px 14px', fontSize: 13, fontWeight: 500, color: 'var(--ink-500)', background: 'none', border: 'none', cursor: 'pointer', fontFamily: "'Geist', 'Inter', system-ui, sans-serif" }}
                                    disabled={isSending}
                                >
                                    Cancel
                                </button>
                                <button
                                    onClick={handleSendEmail}
                                    disabled={isSending || !emailAddress}
                                    style={{ padding: '7px 20px', fontSize: 13, fontWeight: 500, background: 'var(--accent)', color: 'var(--accent-ink)', border: 'none', cursor: isSending || !emailAddress ? 'not-allowed' : 'pointer', opacity: isSending || !emailAddress ? 0.5 : 1, fontFamily: "'Geist', 'Inter', system-ui, sans-serif", display: 'flex', alignItems: 'center', gap: 6 }}
                                >
                                    {isSending ? (
                                        <>
                                            <div style={{ width: 14, height: 14, border: '2px solid var(--accent-ink)', borderTopColor: 'transparent', borderRadius: 14, animation: 'spin 0.6s linear infinite' }} />
                                            Sending...
                                        </>
                                    ) : (
                                        <>
                                            <span className="material-symbols-outlined" style={{ fontSize: 16 }}>send</span>
                                            Send Email
                                        </>
                                    )}
                                </button>
                            </div>
                        )}
                    </div>
                </div>
            )}
        </div>
    );
}
